output_path: /Users/mhb8436/Workspaces/snake8/snakemake-tutorial/output/samples
data_path: /Users/mhb8436/Workspaces/snake8/snakemake-tutorial/data/samples
resource_path: /Users/mhb8436/Workspaces/snake8/snakemake-tutorial/data/reference
bwa_reference: genome.fa